### ISSUE TITLE
Regression test for closing driver while connection pending

### ISSUE THREAD

**Issue by ghost** [PlasmaPHP/driver-mysql#12]
A regression test should be added to the test suite to test that the connection attempt gets cancelled when we close the driver while the connection is still pending.

**Comment by CharlotteDunois** [comment]
IssueId: 35325729  Message: The assignment to ``$unix`` is dead and can be removed.
  Filename: src/Driver.php
  LineNumber: 170
  Link: https://scrutinizer-ci.com/g/PlasmaPHP/driver-mysql/issues/master/files/src/Driver.php?orderField=path&order=asc&honorSelectedPaths=0#&issueId=35325729
